# This is a GitHub Actions workflow for cleaning up resources in the original template. When users create
# a new repository from the template, the workflow deletes and edits files and push a commit.
#
# See: https://github.com/fregante/browser-extension-template/blob/main/.github/workflows/template-cleanup.yml

name: Cleanup template
on:
  push:
    branches: [main]

permissions:
  contents: write

jobs:
  cleanup:
    runs-on: ubuntu-latest
    # Only run job for destination repository
    if: github.event.repository != 'sotayamashita/browser-extension-template'
    steps:
      - uses: actions/checkout@v3

      - name: Cleanup
        run: |
          rm -f \
            .github/workflows/cleanup-template.yml

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Cleanup template
